### ISSUE TITLE
How should Option<T> be serialized?

### ISSUE THREAD

**Issue by mlanghinrichs** [PeytonT/serde_ion#7]
The [serde data model](https://serde.rs/data-model.html) doesn't support type-specific options, instead generalizing option support into Serializer's serialize_some and serialize_none functions. In addition, Nones don't carry any type information (which is generally unavailable through introspection anyhow).

Is there a workaround for this to allow typed nulls, or will conversion simply have to be lossy and force any None into a bare null?

See #2 for the inverse issue.

**Comment by PeytonT** [comment]
From the serde data model page,
> These are a way of mapping every Rust data structure into one of 29 possible types.

This reminds me of the [classification of finite simple groups](https://en.wikipedia.org/wiki/Classification_of_finite_simple_groups), specifically the 26 that are [sporadic](https://en.wikipedia.org/wiki/Sporadic_group).

We may need to seek input from [@dtolnay](https://github.com/dtolnay) on the Serde IRC. Alternatively, we can go back to the idea we shelved of forcing exclusive use of library-exposed Ion types in structs that are serialization/deserialization targets. This would allow us to use the Serde data model support for enum handling, since that's already how we're handling various Nulls in the current Ion IR.

**Comment by mlanghinrichs** [comment]
I'm still opposed to requiring the use of exposed types - could we instead implement a new trait for Option<T> on a per-type basis creating a method which allows a None to return its ion type name?

**Comment by PeytonT** [comment]
If we have the information of what type the option is of (which I think we should?) we can just handle it internally. This probably requires some research.

**Comment by mlanghinrichs** [comment]
As far as I know, the type of generic parameters can't be determined at runtime within the standard library. See [type-info](https://docs.rs/type-info/0.2.1/type_info/) crate for a type-checking trait implementation which appears to be similar to what I described.

**Comment by mlanghinrichs** [comment]
After some investigation, we appear to have little choice as to how Nones are encoded, as no arguments are passed to Serializer's serialize_none(). It seems that we'll have to serialize all Nones as raw null.
